select * from actor;
select first_name, last_name from actor;
select title from film;
select first_name, last_name, email from customer;
select * from payment;
select * from film where rating ='PG';
select * from film where rental_rate>3;
select * from film where rental_rate >= 2 and rating ='PG-13';
select title, rating from film where rating = 'pg' or rating = 'g';
select title, rental_rate from film where rental_rate between 2 and 4;
select title, rating from film where rating in ('PG','G','PG-13');
select * from customer where email is null;
select * from film where title like '%LOVE%';
select * from film where title like 'A%';
select * from film where title like '%MAN';
select * from customer where last_name like "% %";
select * from actor where first_name like '%JO%';
select title, rental_rate from film order by rental_rate desc;
select title, rental_rate from film order by rental_rate desc, rating asc;
select title, rental_rate from film order by rental_rate desc limit 5;
select * from actor limit 10;
select * from customer order by first_name asc limit 20;
select * from film order by rental_Rate asc limit 3;
select distinct rating from film;
select count(*) as 영화수 from film;
select avg(rental_rate) as 평균요금 from film;
select max(rental_rate) as 최고요금 from film;
select Min(rental_rate) as 최저요금 from film;
select SUM(amount) as 총결제금액 from payment;
select avg(amount) as 평균결제금액 from payment;
select count(*) as 영화개수 from film group by rating;
select rating, avg(rental_rate) as 평균대여요금 from film group by rating;
select rating, count(*) 영화수 from film group by rating having count(*) >=200;
select staff_id, sum(amount) 총결제금액 from payment group by staff_id;
select staff_id, sum(amount) 총결제금액 from payment group by staff_id having sum(amount) >=5000;
select customer_id, count(*) 결제횟수 from payment group by customer_id;
select customer_id, count(*) 결제횟수 from payment group by customer_id having count(*) >=30;
select customer_id, sum(amount) 결제금액 from payment group by customer_id;
select c.first_name, c.last_name, r.rental_date from customer c join rental r on c.customer_id = r.customer_id;
select c.customer_id, count(r.rental_id) as 대여횟수 from customer c join rental r on c.customer_id = r.customer_id group by c.customer_id;
select c.customer_id, count(r.rental_id) as 대여횟수 from customer c join rental r on c.customer_id = r.customer_id group by c.customer_id having count(r.rental_id) >=20;
select c.first_name, c.last_name, sum(p.amount) 총결제금액 from customer c join payment p on c.customer_id = p.customer_id group by c.customer_id;
select c.first_name, c.last_name, sum(p.amount) 총결제금액 from customer c join payment p on c.customer_id = p.customer_id group by c.customer_id having sum(p.amount) >=100;
select c.customer_id, sum(p.amount) 총결제금액 from customer c join payment p on c.customer_id = p.customer_id group by c.customer_id order by 총결제금액 desc limit 5;
select c.customer_id, r.rental_id from customer c left join rental r on c.customer_id = r.customer_id;
select c.customer_id from customer c left join rental r on c.customer_id = r.customer_id where r.rental_id is null;
select * from payment where amount <1 or amount is null;
select c.customer_id, count(r.rental_id) 대여횟수, sum(p.amount) from customer c left join rental r on c.customer_id = r.customer_id left join payment p on r.rental_id = p.rental_id group by c.customer_id;
select c.customer_id, count(r.rental_id) 대여횟수, sum(p.amount) from customer c left join rental r on c.customer_id = r.customer_id left join payment p on r.rental_id = p.rental_id group by c.customer_id having count(r.rental_id) >=10 and sum(p.amount) >=50;
select c.customer_id, count(r.rental_id) 대여횟수, sum(p.amount) 총결제금액 from customer c left join rental r on c.customer_id = r.customer_id left join payment p on r.rental_id = p.rental_id group by c.customer_id order by 대여횟수 desc, 총결제금액 desc limit 10;